#!/bin/bash

REPO_URL="http://kxstudio.linuxaudio.org/repo/pool"

set -e

# free
cd packages/free/
for pkg in $(cat ../../dists/stable/free/binary-amd64/Packages | awk 'sub("Filename: pool/free/","")'); do
  wget -c ${REPO_URL}/free/${pkg}
done
for pkg in $(cat ../../dists/stable/free/binary-i386/Packages | awk 'sub("Filename: pool/free/","")'); do
  wget -c ${REPO_URL}/free/${pkg}
done
cd ../..

# free-v5
cd packages/free-v5/
for pkg in $(cat ../../dists/gcc5/free/binary-amd64/Packages | awk 'sub("Filename: pool/free-v5/","")'); do
  wget -c ${REPO_URL}/free-v5/${pkg}
done
for pkg in $(cat ../../dists/gcc5/free/binary-i386/Packages | awk 'sub("Filename: pool/free-v5/","")'); do
  wget -c ${REPO_URL}/free-v5/${pkg}
done
cd ../..
