#!/bin/bash

set -e

rm -f pool/*/*.deb
ln -s $(pwd)/packages/free/*.deb pool/free/
ln -s $(pwd)/packages/free-v5/*.deb pool/free-v5/
# ln -s $(pwd)/packages/non-free/*.deb pool/non-free/
# ln -s $(pwd)/packages/non-free-v5/*.deb pool/non-free-v5/
# ln -s $(pwd)/packages/non-free_bitwig/*.deb pool/non-free_bitwig/
# ln -s $(pwd)/packages/non-free_tracktion/*.deb pool/non-free_tracktion/

apt-ftparchive -a amd64 packages pool/free > dists/stable/free/binary-amd64/Packages
apt-ftparchive -a i386  packages pool/free > dists/stable/free/binary-i386/Packages

apt-ftparchive -a amd64 packages pool/free-v5 > dists/gcc5/free/binary-amd64/Packages
apt-ftparchive -a i386  packages pool/free-v5 > dists/gcc5/free/binary-i386/Packages

apt-ftparchive -a amd64 packages pool/non-free > dists/stable/non-free/binary-amd64/Packages
apt-ftparchive -a i386  packages pool/non-free > dists/stable/non-free/binary-i386/Packages

apt-ftparchive -a amd64 packages pool/non-free-v5 > dists/gcc5/non-free/binary-amd64/Packages
apt-ftparchive -a i386  packages pool/non-free-v5 > dists/gcc5/non-free/binary-i386/Packages

# apt-ftparchive packages pool/non-free_bitwig    >> dists/stable/non-free/binary-amd64/Packages
# apt-ftparchive packages pool/non-free_tracktion >> dists/stable/non-free/binary-amd64/Packages

cat dists/stable/free/binary-amd64/Packages | gzip -c -9 > dists/stable/free/binary-amd64/Packages.gz
cat dists/stable/free/binary-i386/Packages  | gzip -c -9 > dists/stable/free/binary-i386/Packages.gz

cat dists/gcc5/free/binary-amd64/Packages | gzip -c -9 > dists/gcc5/free/binary-amd64/Packages.gz
cat dists/gcc5/free/binary-i386/Packages  | gzip -c -9 > dists/gcc5/free/binary-i386/Packages.gz

cat dists/stable/non-free/binary-amd64/Packages | gzip -c -9 > dists/stable/non-free/binary-amd64/Packages.gz
cat dists/stable/non-free/binary-i386/Packages  | gzip -c -9 > dists/stable/non-free/binary-i386/Packages.gz

cat dists/gcc5/non-free/binary-amd64/Packages | gzip -c -9 > dists/gcc5/non-free/binary-amd64/Packages.gz
cat dists/gcc5/non-free/binary-i386/Packages  | gzip -c -9 > dists/gcc5/non-free/binary-i386/Packages.gz

rm -f dists/stable/Release dists/stable/Release.gpg
rm -f dists/gcc5/Release dists/gcc5/Release.gpg

cp Release.stable.bak Release.stable
cp Release.gcc5.bak Release.gcc5

apt-ftparchive release dists/stable/ >> Release.stable
apt-ftparchive release dists/gcc5/ >> Release.gcc5

mv Release.stable dists/stable/Release
mv Release.gcc5 dists/gcc5/Release

rm -f pool/*/*.deb

gpg --default-key 0AA38242 --output dists/stable/Release.gpg -ba dists/stable/Release
gpg --default-key 0AA38242 --output dists/gcc5/Release.gpg -ba dists/gcc5/Release
