#!/bin/sh

# This is Linux-specific startup script for a bundled version of Ardour

checkdebug(){
    for arg in "$@"
        do
            case "$arg" in
                --gdb )
                    DEBUG="T"
            esac
        done
}

checkdebug "$@"


# LD_LIBRARY_PATH needs to be set here so that epa can swap between the original and the bundled version
# (the original one will be stored in PREBUNDLE_ENV)
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export PREBUNDLE_ENV="$(env)"

BIN_DIR=/opt/ardour/bin
INSTALL_DIR=$(dirname $BIN_DIR)
LIB_DIR=$INSTALL_DIR/lib
ETC_DIR=$INSTALL_DIR/etc

# this triggers code in main() that will reset runtime environment variables
# to point to directories inside the ardour package

export ARDOUR_BUNDLED=true

# NSM needs a path to this script
export ARDOUR_SELF="ardour"

# edited

export LXVST_PATH="$VST_PATH"
export PATH=/opt/ardour/bin:$PATH

# Disable extra modules from being loaded by gtk (example, libcanberra-gtk-module.so)
export GTK_MODULES=""
# Set this so that the executable will find all the right libraries inside the bundle
export LD_LIBRARY_PATH=$INSTALL_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

if [ "T" = "$DEBUG" ]; then
	export ARDOUR_INSIDE_GDB=1
	exec gdb $INSTALL_DIR/bin/ardour-5.6.22
else
	exec  $INSTALL_DIR/bin/ardour-5.6.22 "$@"
fi
